config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  # root 'posts#index'
  resources :posts
  get '/signin' => 'auth#signin'
  get '/signup' => 'auth#signup'
  post '/signin' => 'auth#new_session', as: 'new_session'
  post '/signup' => 'auth#new_account', as: 'new_account'
  delete '/logout' => 'auth#logout'

  get '/home' => 'user#index'

  get '/user/:id' => 'user#show', as: 'user'
  get '/user/:id/edit' => 'user#edit', as: 'edit_user'
  patch '/user/:id' => 'user#update'
  delete '/user/:id' => 'user#delete'

  get '/transactions/index' => 'transactions#index'

  get '/transactions/:symbol/buy' => 'transactions#buy_stock', as: 'transactions_buy'
  # post '/transactions/buy_stock/:symbol' => 'transactions#buy'
  
  get '/transactions/:symbol/sell' => 'transactions#sell_stock', as: 'transactions_sell'
  # post '/transactions/sell_stock/:symbol' => 'transactions#sell'

  post '/transactions/:symbol' => 'transactions#save_transaction', as: 'save_transaction'

  get '/portfolio/index' => 'portfolio#index'

  # post '/admin/dashboard' => 'admin/dashboard#create', as: 'create_admin_dashboard'
  get 'admin/dashboard/pendingusers' => 'admin/dashboard#pending_users', as: 'pending_users'
  namespace :admin do 
    resources :dashboard
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
    layout 'admin/base'
    # before_action :get_user
    
    def index
        # @users = User.all
        # admin/dashboard
        @cur_user = current_user

        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true)
    end

    def show
        @user = User.find(params[:id])
        @cur_user = current_user
    end

    def pending_users
        @users = User.all
        @cur_user = current_user
    end

    #get /new
    def new 
        @user = User.new
        @cur_user = current_user
    end

    # POST /new
    def create
       @user = User.new(user_params)

       if @user.save
        redirect_to admin_dashboard_index_path
       else
        render :new, status: :unprocessable_entity
       end
    end

    def edit
        @user = User.find(params[:id])
        @cur_user = current_user
    end

    def update 
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to admin_dashboard_path(@user.id)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy

        if @user.email_verification?
            redirect_to admin_dashboard_index_path
        else
            redirect_to pending_users_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :balance)
    end

    def signup_params
        params.permit(:email, :password, :password_confirmation)
    end

    # def get_user
    #     @user = User.find_by(session[:token])

    #     if @user.admin?
    #         redirect_to admin_dashboard_index_path
    #     end
    # end

end

app/views/admin/dashboard/_form.html.erb
<div class="w-full ">
    <%= form_with model: @user, url: path, local: true do |f| %>

    <div class="mx-96">

        <div class="mt-5">
            <%= f.label "Email", class: "block"%>
            <%= f.email_field :email, placeholder: "Juan@gmail.com", class: "w-full rounded"%>
        </div>

        <div class="mt-5">
            <%= f.label "Password", class: "block" %>
            <%= f.password_field :password, placeholder: "Password", class: "w-full rounded" %>
        </div>

        <div class="mt-5">
            <%= f.label "Confirm Password", class: "block"%>
            <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "w-full rounded" %>
        </div>

        <div class="mt-5">
            <%= f.label "Balance", class: "block"%>
            <%= f.number_field :balance, placeholder: "Juan@gmail.com", class: "w-full rounded" %>
        </div>

        <div class="mt-5">
            <%= f.submit "Submit", class: 'rounded bg-[#01161E] text-white p-2 cursor-pointer w-full hover:bg-[#22414d]' %>
        </div>

        <% end %>
    </div>

</div>

app/views/admin/dashboard/_search_form.html.erb
<%= form_with model: @user, url: admin_dashboard_index_path, local: true do |f| %>
    <%= f.text_field :search, placeholder: "Search here...", class: "w-full rounded search font-bold"%>
<% end %>

app/views/admin/dashboard/_sidebar.html.erb
<div class="h-screen top-0 left-0 flex flex-col w-72 bg-[#01161E] text-white border-r-2 border-[#728C69]">
    <div class="flex flex-col justify-between flex-1">
        <div class="border-[#4A6FA5] mb-4 p-3">
            <p class="w-[55px] mt-5"><%= link_to image_tag("bull-market (1).png"), root_path %></p>
          
            <div class="mt-5">
                <%= render "search_form"%>
            </div>
        </div>

        <div class="flex-1 ">
                <ul>
                    <li class="text-2xl hover:bg-[#afbfa4] hover:text-[#01161E] p-3"><%= link_to "Active Users", admin_dashboard_index_path %></li>
                    <li class="text-2xl hover:bg-[#afbfa4] hover:text-[#01161E] p-3"><%= link_to "Create New User", new_admin_dashboard_path %></li>
                    <li class="text-2xl hover:bg-[#afbfa4] hover:text-[#01161E] p-3"><%= link_to "Pending Users", pending_users_path %></li>
                <ul>
        </div>

        <div class="p-3">
            <div class="bg-[#142F43] p-3 rounded-lg ">
                <p class="font-bold text-lg">Latest Trade News</p>
                <p class="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus harum officia eligendi velit.</p>
                <p class="mt-5 rounded-full"><%= link_to image_tag("news.jpg", class: "rounded"), admin_dashboard_index_path%></p>
            </div>
        </div>

        <div class="border-t flex justify-between items-center p-5 mt-3">
            <div class="flex items-center gap-x-2">
                <%= image_tag('dp.png', class: "w-[25px]")%>
                <h1 class=""><%= @cur_user.email.split("@")[0].capitalize  %></h1>
            </div>

            <div>
                <%= button_to "Log Out" ,logout_path, method: :delete, class: ""  %>
            </div>
        </div>
    </div>
</div>

app/views/admin/dashboard/edit.html.erb
<div class="bg h-screen w-full text-black relative">
        <div class="flex flex-row">
            <%= render "sidebar"%>
             <div class="w-full">
                <h1 class="text-center text-5xl mt-5">Edit User</h1>
                    <div class="">
                    <%= render "form", scope: :user, path: admin_dashboard_path %>
                    </div>
        </div>
</div>



app/views/admin/dashboard/index.html.erb
<div class="bg h-screen w-full text-black relative ">
    <div class="flex flex-row">
        <%= render "sidebar"%>
        <div class="flex flex-col">
        <h1 class="text-center text-5xl mt-5">Active Users</h1>

            <table class="table-auto border border-slate-500 ml-5">
                <thead>
                    <tr>
                        <th class="border border-slate-600 py-3">Email</th>
                        <th class="border border-slate-600 py-3">ID No.</th>
                        <th class="border border-slate-600 py-3">Verified</th>
                        <th class="border border-slate-600 py-3">Create At</th>
                        <th class="border border-slate-600 py-3">Balance</th>
                        <th class="border border-slate-600 py-3" colspan='3'>Actions</th>
                    </tr>
                </thead>

                <tbody class="">
                <% @users.each do |user|%>
                <% if !user.admin && user.email_verification %>
                    <tr class="hover:text-white">
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.email%></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.id%></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.email_verification%></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.created_at%></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.balance %></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl "><%= link_to 'View', admin_dashboard_path(user.id) %></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= link_to 'Edit', edit_admin_dashboard_path(user.id) %></td>
                        <td class="border border-slate-700 py-3 px-6 text-2xl"><%= button_to "Delete", admin_dashboard_path(user.id), method: :delete %></td>
                    </tr>
                        <% end%>
            <% end%>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/admin/dashboard/new.html.erb
<div class="bg h-screen w-full text-black relative">
        <div class="flex flex-row">
            <%= render "sidebar"%>
                <div class="w-full">
                    <h1 class="text-center text-5xl mt-5">Create New User</h1>
                        <div class="">
                            <%= render "form", scope: :user, path: admin_dashboard_index_path %>
                        </div>
                </div>
        </div>
</div>



app/views/admin/dashboard/pending_users.html.erb
<div class="bg h-screen w-full text-black relative">
<div class="flex flex-row">
<%= render "sidebar"%>
<div class="flex flex-col">
<h1 class="text-center text-5xl mt-5">Pending Users</h1>

<table class="table-auto border border-slate-500 ml-5 ">
    <thead>
        <tr>
            <th class="border border-slate-600 py-3">Email</th>
            <th class="border border-slate-600 py-3">ID No.</th>
            <th class="border border-slate-600 py-3">Verified</th>
            <th class="border border-slate-600 py-3">Created At</th>
            <th class="border border-slate-600 py-3">Balance</th>
            <th class="border border-slate-600 py-3" colspan='3'>Actions</th>
        </tr>
    </thead>

    <tbody>
    <% @users.each do |user|%>
    <% if !user.admin && !user.email_verification %>
        <tr class="hover:text-white">
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.email%></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.id%></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.email_verification%></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.created_at%></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= user.balance %></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= link_to 'View', admin_dashboard_path(user.id) %></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= link_to 'Edit', edit_admin_dashboard_path(user.id) %></td>
            <td class="border border-slate-700 py-3 px-6 text-2xl"><%= button_to "Delete", admin_dashboard_path(user.id), method: :delete %></td>
        </tr>
            <% end%>
<% end%>
    </tbody>
</table>


    <p></p>


</div>
</div>
</div>

app/views/admin/dashboard/show.html.erb
<div class="bg h-screen w-full text-black relative">
    <div class="flex flex-row">
    <%= render "sidebar"%>
        <div class="flex flex-col ml-5">
            <p class="text-4xl mt-5 font-bold">Email: <span class="font-thin"><%= @user.email%></span></p>
            <p class="text-4xl mt-5 font-bold">ID:<span class="font-thin"> <%= @user.id%></span></p>
            <p class="text-4xl mt-5 font-bold">Balance: <span class="font-thin"><%= @user.balance%></span></p>
            <p class="text-4xl mt-5 font-bold">Created At: <span class="font-thin"><%= @user.created_at %></span></p>
            <p class="text-4xl mt-5 font-bold">Stocks Owned: 
            <span class="font-thin"><% @user.user_stocks.each do |stock|%>
                <%= stock.symbol %>
            <% end %></span>
            </p>
        </div>
    </div>
</div>