config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  # root 'posts#index'
  resources :posts
  get '/signin' => 'auth#signin'
  get '/signup' => 'auth#signup'
  post '/signin' => 'auth#new_session', as: 'new_session'
  post '/signup' => 'auth#new_account', as: 'new_account'
  delete '/logout' => 'auth#logout'

  get '/home' => 'user#index'

  get '/user/:id' => 'user#show', as: 'user'
  get '/user/:id/edit' => 'user#edit', as: 'edit_user'
  patch '/user/:id' => 'user#update'
  delete '/user/:id' => 'user#delete'

  get '/transactions/index' => 'transactions#index'

  get '/transactions/:symbol/buy' => 'transactions#buy_stock', as: 'transactions_buy'
  # post '/transactions/buy_stock/:symbol' => 'transactions#buy'
  
  get '/transactions/:symbol/sell' => 'transactions#sell_stock', as: 'transactions_sell'
  # post '/transactions/sell_stock/:symbol' => 'transactions#sell'

  post '/transactions/:symbol' => 'transactions#save_transaction', as: 'save_transaction'

  get '/portfolio/index' => 'portfolio#index'

  # post '/admin/dashboard' => 'admin/dashboard#create', as: 'create_admin_dashboard'
  get 'admin/dashboard/pendingusers' => 'admin/dashboard#pending_users', as: 'pending_users'
  namespace :admin do 
    resources :dashboard
  end

end

app/views/partials/_sidebar.html.erb
<div class="h-screen top-0 left-0 flex flex-col w-72 bg-[#01161E] text-white border-r-2 border-[#728C69]">
    <div class="flex flex-col justify-between flex-1">
        <div class="border-[#4A6FA5] mb-4 p-3">
            <p class="w-[55px] mt-5"><%= link_to image_tag("bull-market (1).png"), root_path %></p>

            <div class="mt-5">
                <%= form_with model: @transaction, url: root_path, local: true do |f| %>
                    <%= f.text_field :search, placeholder: "Search here...", class: "w-full rounded search font-bold p-2"%>
                <% end %>
            </div>
        </div>

        <div class="flex-1 ">
                <ul>
                    <li class="text-2xl hover:bg-[#728C69] hover:text-[#01161E] p-3 cursor-pointer flex gap-2">
                    <%= image_tag("briefcase", class: "w-4, h-7") %> <%= link_to "Portfolio", portfolio_index_path  %>
                    </li>

                    <li class="text-2xl hover:bg-[#728C69] hover:text-[#01161E] p-3 cursor-pointer flex gap-2">
                    <%= image_tag("arrow.png", class: "w-4, h-7")%><%= link_to "Bull Hunt"  %>
                    </li>

                    <li class="text-2xl hover:bg-[#728C69] hover:text-[#01161E] p-3 cursor-pointer flex gap-2">
                    <%= image_tag("trend.png", class: "w-4, h-7")%><%= link_to "Dead Stocks"  %>
                    </li>
                <ul>
        </div>

        <div class="p-3">
            <div class="bg-[#142F43] p-3 rounded-lg ">
                <p class="font-bold text-lg">Latest Trade News</p>
                <p class="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus harum officia eligendi velit.</p>
                <p class="mt-5 rounded-full"><%= link_to image_tag("news.jpg", class: "rounded"), root_path%></p>
            </div>
            <p class="text-lg mt-2 text-center">Current Balance: <%= @user.balance%></p>
        </div>

        <div class="border-t flex justify-between items-center p-5">
            <div class="flex items-center gap-x-2">
                <%= image_tag('dp.png', class: "w-[25px]")%>
                <h1 class=""><%= @user.email.split("@")[0].capitalize  %></h1>
            </div>

            <div>
                <%= button_to "Log Out" ,logout_path, method: :delete, class: ""  %>
            </div>
        </div>
    </div>
</div>