config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  # root 'posts#index'
  resources :posts
  get '/signin' => 'auth#signin'
  get '/signup' => 'auth#signup'
  post '/signin' => 'auth#new_session', as: 'new_session'
  post '/signup' => 'auth#new_account', as: 'new_account'
  delete '/logout' => 'auth#logout'

  get '/home' => 'user#index'

  get '/user/:id' => 'user#show', as: 'user'
  get '/user/:id/edit' => 'user#edit', as: 'edit_user'
  patch '/user/:id' => 'user#update'
  delete '/user/:id' => 'user#delete'

  get '/transactions/index' => 'transactions#index'

  get '/transactions/:symbol/buy' => 'transactions#buy_stock', as: 'transactions_buy'
  # post '/transactions/buy_stock/:symbol' => 'transactions#buy'
  
  get '/transactions/:symbol/sell' => 'transactions#sell_stock', as: 'transactions_sell'
  # post '/transactions/sell_stock/:symbol' => 'transactions#sell'

  post '/transactions/:symbol' => 'transactions#save_transaction', as: 'save_transaction'

  get '/portfolio/index' => 'portfolio#index'

  # post '/admin/dashboard' => 'admin/dashboard#create', as: 'create_admin_dashboard'
  get 'admin/dashboard/pendingusers' => 'admin/dashboard#pending_users', as: 'pending_users'
  namespace :admin do 
    resources :dashboard
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :set_stock

    def index
        @transactions = current_user.transactions
    end

    # get buy stock
    def buy_stock
        @user = current_user
        @transaction = Transaction.new
        @quote = IEX_CLIENT.quote(params[:symbol])
    end

    # get sell stock
    def sell_stock
        @user = current_user
        @transaction = Transaction.new
        @quote = IEX_CLIENT.quote(params[:symbol])
    end

    def save_transaction
      @transaction = current_user.transactions.create(set_transactions)
      @transaction.amount = @transaction.total_price

      @user_stock = current_user.user_stocks.find_or_create_by(symbol: buy_params[:symbol], company_name: buy_params[:company_name])
      updated_quantity = @transaction.calculate_new_quantity(@user_stock.quantity)

      if @transaction.save && @user_stock.update(quantity: updated_quantity)
        current_user.update!(:balance => current_user.balance - @transaction.amount )
        redirect_to root_path
      else
        if @transaction.buy?
            redirect_to transactions_buy_path
        else
            redirect_to transactions_sell_path
        end
      end
    
    end


    
    private

    def buy_params
        params.require(:transaction).permit(:symbol, :company_name, :price, :quantity)
    end

    def set_stock
        @stock = UserStock.find_by(symbol: params[:symbol], company_name: params[:company_name], quantity: params[:quantity])
    end

    def set_transactions
       params.require(:transaction).permit(:symbol, :price, :quantity, :kind)
    end

end

app/views/transactions/buy_stock.html.erb
<div class="bg h-screen w-full text-black relative">
    <div class="flex flex-row">
        <%= render "partials/sidebar"%>
        <div class="flex flex-col w-[1200px] mx-auto">
            
            <div class="w-full">
                <%= form_with model: @transaction, url: save_transaction_path, local: true do |f| %>
                <%= f.hidden_field :kind, value: "buy" %>
                <h1 class="text-center text-5xl mt-5">Buy Stock</h1>
                <div class="">

                    <div class="">
                        <%= f.label "Quantity", class: "block text-2xl"%>
                        <%= f.number_field :quantity, class: "w-full rounded text-2xl p-4"%>
                    </div>

                    <div class="mt-5">
                        <%= f.label "Price", class: "block text-2xl" %>
                        <%= f.number_field :price, value: @quote.latest_price, class: "w-full rounded text-2xl p-4" %>
                    </div>

                    <div class="mt-5">
                        <%= f.label "Company Name", class: "block text-2xl"%>
                        <%= f.text_field :company_name, value: @quote.company_name , class: "w-full rounded text-2xl p-4" %>
                    </div>

                    <div class="mt-5">
                        <%= f.label "Symbol", class: "block text-2xl"%>
                        <%= f.text_field :symbol, value: params[:symbol] , class: "w-full rounded text-2xl p-4" %>
                    </div>

                    <div class="mt-5">
                        <%= f.submit "Buy", class: 'rounded bg-[#01161E] text-2xl text-white p-2 cursor-pointer w-full hover:bg-[#22414d]' %>
                    </div>

                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/transactions/index.html.erb
<%= @transactions.inspect %>

app/views/transactions/sell_stock.html.erb
<div class="bg h-screen w-full text-black relative">
    <div class="flex flex-row">
        <%= render "partials/sidebar"%>
        <div class="flex flex-col w-[1200px] mx-auto">
                <div class="w-full">
                <%= form_with model: @transaction, url: save_transaction_path, local: true do |f| %>
                <%= f.hidden_field :kind, value: "sell" %>
                    <h1 class="text-center text-5xl mt-5">Sell Stock</h1>
                    <div class="">

                        <div class=" w-full">
                            <%= f.label "Quantity", class: "block text-2xl"%>
                            <%= f.number_field :quantity, class: "w-full rounded text-2xl p-4"%>
                        </div>

                        <div class="mt-5">
                            <%= f.label "Price", class: "block text-2xl" %>
                            <%= f.number_field :price, value: @quote.latest_price, class: "w-full rounded text-2xl p-4" %>
                        </div>

                        <div class="mt-5">
                            <%= f.label "Company Name", class: "block text-2xl"%>
                            <%= f.text_field :company_name, value: @quote.company_name , class: "w-full rounded text-2xl p-4" %>
                        </div>

                        <div class="mt-5">
                            <%= f.label "Symbol", class: "block text-2xl"%>
                            <%= f.text_field :symbol, value: params[:symbol] , class: "w-full rounded text-2xl p-4" %>
                        </div>

                        <div class="mt-5">
                            <%= f.submit "Sell", class: 'rounded bg-[#01161E] text-2xl text-white p-2 cursor-pointer w-full hover:bg-[#22414d]' %>
                        </div>

                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>
